#ifndef __PP_analyzer
#define __PP_analyzer

#include <pp_decap.h>
#include <pp_flow.h>

/**
 * each analyzer is invoked on each packet
 *
 *
 * the describe function must deliver a JSON string that contains the
 * description of the analyzer according XXXXX TODO
 */

enum PP_ANALYZER_MODES {
	PP_ANALYZER_MODE_UNKNOWN = 0,
	/* keep all collected data (may conusme all available memory) */
	PP_ANALYZER_MODE_INFINITY,
	/* only keep collected data within given timestamp
	 * time given in milliseconds
	 */
	PP_ANALYZER_MODE_TIMESPAN,
	/* only keep collected data for last PACKETCOUNT packets */
	PP_ANALYZER_MODE_PACKETCOUNT,
	PP_ANALYZER_MODE_EOL
};

/* actions reqeusted by the analyzer after handling
 * the current packet inside of the inspect function
 */
enum PP_ANALYZER_ACTION {
	PP_ANALYZER_ACTION_NONE = 0,
	PP_ANALYZER_ACTION_DROP,
	PP_ANALYZER_ACTION_FORWARD,
	PP_ANALYZER_ACTION_DELAY,
	PP_ANALYZER_ACTION_EOL
};

struct pp_analyzer {

	/* analyzer index - references the data entry inside of the flow */
	uint32_t idx;

	/* inspect current packet function
	 * this function is called for each packet
	 * invoked by: packet handler
	 * */
	enum PP_ANALYZER_ACTION (*inspect)(uint32_t idx,struct pp_packet_context *pkt_ctx, struct pp_flow *flow_ctx);

	/* analyze function
	 * runs an analysis over the collected data
	 * invoked by: manually, before calling report
	 * can be NULL
	 * */
	void (*analyze)(uint32_t idx,struct pp_flow *flow_ctx);

	/* report function
	 * return the report generated by the analyzer
	 * invoked by: manually, by the packet prozessor (user request, on exit)
	 * can be NULL
	 * */
	char* (*report)(uint32_t idx,struct pp_flow *flow_ctx);

	/* self description function
	 * returns a short description of the analyzer
	 * invoked by: manually, help function
	 * */
	char* (*describe)(struct pp_flow *flow_ctx);

	/* init function
	 * creates the context of the analyzer
	 * invoked by: on startup by the packet prozessor
	 * */
	void (*init)(uint32_t idx,struct pp_flow *flow_ctx, enum PP_ANALYZER_MODES mode, uint32_t mode_val);

	/* cleanup function
	 * destroys the context of the analyzer, frees all used data
	 * invoked by: on exit by the packet prozessor
	 * */
	void (*destroy)(uint32_t idx,struct pp_flow *flow_ctx);

	/* holds analyzer specific data */
	void *usr_ptr;

	/* point to the next analyzer in the chain */
	struct pp_analyzer *next_analyzer;
};

int pp_analyzer_register(struct pp_analyzer **analyzer_list,
						 enum PP_ANALYZER_ACTION (*inspect)(uint32_t idx, struct pp_packet_context *pkt_ctx, struct pp_flow *flow_ctx),
						 void (*analyze)(uint32_t idx, struct pp_flow *flow_ctx),
						 char* (*report)(uint32_t idx, struct pp_flow *flow_ctx),
						 char* (*describe)(struct pp_flow *flow_ctx),
						 void (*init)(uint32_t idx, struct pp_flow *flow_ctx, enum PP_ANALYZER_MODES mode, uint32_t mode_val),
						 void (*destroy)(uint32_t idx, struct pp_flow *flow_ctx),
						 void *usr_ptr);

/**************************************************************/
/* macros and functions for analyzer independent data storage */
/**************************************************************/

/* take memory in chunks of slot-step elements */
#define PP_ANALYZER_SLOT_STEP	100

/* macro to greate analyzer storage struct */
#define PP_ANALYZER_STORE_CREATE(ANALYZER_NAME, DATATYPE) \
struct ANALYZER_NAME { \
	enum PP_ANALYZER_MODES mode;  \
	uint32_t mode_val; \
	uint32_t slot_size; \
	uint64_t write_pos; \
	uint32_t available_slots; \
	uint32_t used_slots; \
	struct ANALYZER_NAME ## _data { \
		uint64_t timestamp; \
		enum __pp_packet_direction direction; \
		struct ANALYZER_NAME ## _data *next; \
		/* keep analyzer related parts below this line */ \
		DATATYPE data; \
	} *entries; \
	struct ANALYZER_NAME ## _data *head_entry; \
	struct ANALYZER_NAME ## _data *tail_entry; \
};

/* create a dummy struct that can be used to access the generic attributes */
PP_ANALYZER_STORE_CREATE(pp_analyzer_store_void, void*);

#define ptr_struct_member_size(type) sizeof(*((struct type *)0)->entries)

/* macro to init an analyzer specific storage inside of a given flow */
#define PP_ANALYZER_STORE_INIT(ANALYZER_NAME, ANALYZER_INDEX, FLOW, MODE, MODE_VAL) pp_analyzer_storage_init_int(ANALYZER_INDEX, FLOW, ptr_struct_member_size(ANALYZER_NAME), MODE, MODE_VAL)
int pp_analyzer_storage_init_int(uint32_t idx, struct pp_flow *flow_ctx, int slot_size, uint32_t mode, int mode_val);

void* pp_analyzer_storage_get_next_location(uint32_t idx, struct pp_packet_context *pkt_ctx, struct pp_flow *flow_ctx);

int pp_analyzer_callback_for_each_entry(uint32_t idx, struct pp_flow *flow_ctx, void (*fnct)(void* entry, uint64_t ts, int direction));

void pp_analyzer_storage_destroy(uint32_t idx, struct pp_flow *flow_ctx);



#endif /* __PP_analyzer */
